plugins { id 'com.android.application' }

android {
    namespace 'com.ecb.efootballcompetitionbet'
    compileSdk 35
    buildFeatures { buildConfig true }

    defaultConfig {
        applicationId 'com.ecb.efootballcompetitionbet'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }
    buildTypes {
        debug { debuggable true }
        release { minifyEnabled false; debuggable false }
    }
}
