// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udwsxqdegrtaqlbwnrqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkd3N4cWRlZ3J0YXFsYnducnFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxOTY0MTcsImV4cCI6MjEwMTc3MjQxN30.T2Y-mkeXqJvksELFt2TZ3YZmMldH8rk0fpnsaL_32tE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});